### ISSUE TITLE
Incorrect output for one-syllable words and pseudo-words beginning with Y

### ISSUE THREAD

**Issue by paulvonhippel** [ellipse-liu/eng-syl#4]
The following one-syllable Y** words are incorrectly classified as two syllables.

Input:
```
from eng_syl.syllabify import Syllabel
syllabler = Syllabel()
print(syllabler.syllabify("yam"))
print(syllabler.syllabify("yip"))
print(syllabler.syllabify("yum"))
print(syllabler.syllabify("yet"))
```
Output:
```
y-am
y-ip
y-um
y-et
```

**Comment by timo-liu** [comment]
I've update the package with a new model, so it should be better at handling pseudowords. I've also incorporated data from the wikimorph dataset for real-english words, so orthographically ambiguous real words should be parsed and returned correctly syllabified now. Go ahead an try out the new package. The edge cases that you raised before have all been tested and verified to work correctly.

**Comment by paulvonhippel** [comment]
Confirmed! All the words I reported previously now return correct output.
